server:
  port:
    8488
###Es 服务器配置
es:
  server:
    ip: 10.23.10.150
    port: 9200

### mybatis
mybatis:
  mapper-locations: /mybatis-mapper/*Mapper.xml
  configuration:
    #为null处理
    call-setters-on-nulls: true
    #设置是否驼峰
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  thymeleaf:
    prefix:
      classpath: /templates   # 访问template下的html文件需要配置模板，映射
    cache: false # 开发时关闭缓存,不然没法看到实时页面



