server:
  port:
    8488
###Es 服务器配置
es:
  server:
    ip: 10.23.10.150
    port: 9200

### mybatis
mybatis:
  mapper-locations: /mybatis-mapper/*Mapper.xml
  configuration:
    #为null处理
    call-setters-on-nulls: true
    #设置是否驼峰
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root


