server:
  port:
    8488
###Es 服务器配置
es:
  server:
    ip: 10.23.10.150
    port: 9200

### mybatis
mybatis:
  mapper-locations: /mybatis-mapper/*Mapper.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
#    tomcat:
#      max-wait: 10000
#      max-active: 30
#      test-on-borrow: true
#      validation-query: SELECT 1
#      validation-interval: 30000

